# Site settings
title: DreamYoungs's Blog
baseurl: "https://dreamyoungs.github.io"

# Gems
gems:
  - jekyll-paginate
  - jekyll-test-plugin
  - jekyll-jsonify
  - jekyll-assets

# Build settings
markdown: kramdown

# http://jekyllrb-ko.github.io/docs/permalinks/
permalink: "/:categories/:title"

# http://jekyllrb-ko.github.io/docs/pagination/
paginate: 2
paginate_path: "/page:num/"

# User Setting
post_img: "/assets/post"
og_img: "/assets/ogimage"
css_route: "/public_html/css/"
js_route: "/public_html/js/"
